name: github-actions-test1
run-name: ${{ github.actor }} triggered the run
on: 
  push:
    branches:
      main
  workflow_dispatch:
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - 
        run: echo "my first workflow"